name: Python Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: unbuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with unittest
        run: |
        python m -unittest discover
          